#!/usr/bin/env python3
"""Generate a Zeon skill that moves the left arm to a captured joint pose.

Takes a name, the left arm's captured joint angles (radians, 6 values) and
gripper width (metres), and writes skills/<name>/{metadata.yaml, modules.py,
robotic_code.py}. The generated skill only ever commands the left arm — it
never touches the right arm, so whatever the right arm is doing (e.g. holding
a plate from a prior step) is left completely undisturbed.

Motion is driven by move_arm_js (joint angles), not move_arm (TCP/IK), per
this project's convention that joint-space relocation has no IK solve to
fail. The TCP pose is optional and, if given, is recorded only as a
reference comment — it does not drive any motion.

Usage:
    python scripts/generate_left_arm_pose_skill.py <name> \
        --joints j1 j2 j3 j4 j5 j6 \
        --gripper width_m \
        [--tcp x y z roll pitch yaw] \
        [--speed speed] \
        [--force]

Writes into skills/<name>/ relative to the repo root (this script's parent
directory's parent, i.e. run it from anywhere inside the project).
"""

import argparse
import re
import sys
from pathlib import Path

SKILL_ID_RE = re.compile(r"^[a-z0-9_]+$")


def find_repo_root(start: Path) -> Path:
    """Walk upward from `start` looking for a `skills/` directory."""
    for candidate in [start, *start.parents]:
        if (candidate / "skills").is_dir():
            return candidate
    raise SystemExit(
        f"Could not find a 'skills/' directory above {start} — run this from "
        "inside the zeon project (or pass an absolute path)."
    )


def render_robotic_code(name: str, joints: list, gripper_width: float, speed: float, tcp) -> str:
    joints_repr = ", ".join(f"{v:.6f}" for v in joints)
    tcp_comment = ""
    if tcp is not None:
        tcp_repr = ", ".join(f"{v:.6f}" for v in tcp)
        tcp_comment = f"# Captured TCP pose (reference only, does not drive motion):\n# [{tcp_repr}]  # [x, y, z, roll, pitch, yaw], metres/radians\n"

    return f'''from .modules import move_arm_js, print_log, set_gripper

# Captured left-arm joint pose (radians, 6-DOF). Generated by
# scripts/generate_left_arm_pose_skill.py — edit by hand if you re-capture,
# or re-run the generator.
{tcp_comment}LEFT_ARM_JOINTS = [{joints_repr}]
GRIPPER_WIDTH_M = {gripper_width:.6f}


def {name}():
    """Move the left arm to a captured joint pose and set the gripper.

    Only ever commands the left arm — never touches the right arm, so
    whatever it is doing (e.g. holding a plate from a prior step) is left
    completely undisturbed.
    """
    print_log(runlog=True, runlog_type="step_start")
    print_log("Starting {name}")

    move_arm_js(arm="left_arm", joint_angles=LEFT_ARM_JOINTS, speed={speed})
    set_gripper(arm="left_arm", width_m=GRIPPER_WIDTH_M)

    print_log("{name} completed")
    return {{"success": True}}
'''


def render_metadata(name: str) -> str:
    return f'''skill_id: {name}
version: "1.0.0"
description: "Move the left arm to a captured joint pose and set the gripper. Generated from a captured pose, not an anchor — only valid for the arm configuration it was captured against. Never touches the right arm."

# parameters are derived from the {name}() signature in robotic_code.py

tags:
  - generated
  - pose_capture
'''


def render_modules() -> str:
    return "from execution.execution_functions import *\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("name", help="skill_id / folder name, e.g. 'left_arm_pose_1' (must match ^[a-z0-9_]+$)")
    parser.add_argument("--joints", type=float, nargs=6, required=True, metavar=("J1", "J2", "J3", "J4", "J5", "J6"),
                         help="left arm joint angles, radians")
    parser.add_argument("--gripper", type=float, required=True, metavar="WIDTH_M",
                         help="gripper width in metres to set at this pose")
    parser.add_argument("--tcp", type=float, nargs=6, default=None, metavar=("X", "Y", "Z", "ROLL", "PITCH", "YAW"),
                         help="optional captured TCP pose, recorded as a reference comment only")
    parser.add_argument("--speed", type=float, default=0.5, help="move_arm_js speed (default: 0.5, matches this project's staging moves)")
    parser.add_argument("--force", action="store_true", help="overwrite an existing skill directory of the same name")
    args = parser.parse_args()

    if not SKILL_ID_RE.match(args.name):
        raise SystemExit(f"Invalid skill name {args.name!r} — must match ^[a-z0-9_]+$ (lowercase, digits, underscores).")

    repo_root = find_repo_root(Path(__file__).resolve().parent)
    skill_dir = repo_root / "skills" / args.name

    if skill_dir.exists() and not args.force:
        raise SystemExit(f"{skill_dir} already exists — pass --force to overwrite.")

    skill_dir.mkdir(parents=True, exist_ok=True)
    (skill_dir / "robotic_code.py").write_text(
        render_robotic_code(args.name, args.joints, args.gripper, args.speed, args.tcp), encoding="utf-8"
    )
    (skill_dir / "metadata.yaml").write_text(render_metadata(args.name), encoding="utf-8")
    (skill_dir / "modules.py").write_text(render_modules(), encoding="utf-8")

    print(f"Wrote {skill_dir}")


if __name__ == "__main__":
    main()
