# -*- coding: utf-8 -*-
HEADER = "paper_id\tverdict\treason\tspecies\tstrain\tcell_source\tgrowth_factor\tconc_value\tconc_unit\tculture_days\tbase_medium\tline"
R = []
def inc(pid, species, strain, source, gf, cv, cu, days, med, line, reason=""):
    R.append([pid,"included",reason,species,strain,source,gf,cv,cu,days,med,line])
def exc(pid, reason, line="NA", species="NA", strain="NA", source="NA", gf="NA", cv="NA", cu="NA", days="NA", med="NA"):
    R.append([pid,"excluded",reason,species,strain,source,gf,cv,cu,days,med,line])

M="mouse"; NR="NR"

# 1
exc("PMC12041772","Human bone marrow / PBMC monocyte-derived macrophages (M-CSF 100 ng/ml, 7 d) - human cells","L28","human","NA","human bone marrow and PBMC","M-CSF","100","ng/ml","7","alpha-MEM + 10% FCS")
# 2
inc("PMC11976235",M,"C57BL/6NCrl","bone marrow cells (femur/tibia)","M-CSF","40","ng/mL","7","complete DMEM","L37","M-CSF 40 ng/mL at seeding, replenished with 20 ng/mL on day 3; 3 d + 4 d incubation")
# 3
inc("PMC11964487",M,NR,"mouse bone marrow mononuclear cells (BMNCs)","M-CSF (Mcsf)",NR,"NA","3","DMEM","L34,L75","M0 stage: Mcsf alone for first 3 days; concentration not stated")
inc("PMC11964487","rat","Lewis rat","rat bone marrow mononuclear cells (BMNCs)","M-CSF (Mcsf)",NR,"NA","3","DMEM","L34,L75","Rat BMNC arm of the same protocol; Mcsf alone for first 3 days")
exc("PMC11964487","IL-4 addition on days 4-5 is M2 polarization, not differentiation","L75",M,NR,"BMNC","IL-4",NR,"NA","2","DMEM")
# 4
inc("PMC12234436",M,NR,"bone marrow (murine progenitors)","L929 cell-conditioned medium","30","% v/v","5-7","DMEM + 20% FBS","L30")
inc("PMC12234436",M,NR,"bone marrow (murine progenitors)","recombinant murine M-CSF","20","ng/mL","5-7","DMEM + 20% FBS","L30","Alternative differentiation to L929-conditioned medium")
inc("PMC12234436","Peromyscus leucopus","deer mouse (P. leucopus)","bone marrow","HEK293T-derived P. leucopus M-CSF supernatant","30","% v/v","6","DMEM + 20% heat-inactivated FBS","L31,L50","Rodent (deer mouse) bone marrow")
# 5
inc("PMC11381776",M,"BALB/c","bone marrow cells (femur/tibia)","M-CSF","50","ng/mL","5","DMEM/F12 + 10% FBS","L38,L47","BMDMs detached on Day 5 of the STAR protocol timeline")
# 6
exc("PMC12021583","Bone marrow-derived dendritic cell protocol (GM-CSF + IL-4)","L130",M,NR,"bone marrow","GM-CSF + IL-4","5","ng/mL","NR","RPMI")
# 7
inc("PMC3003694",M,"C57BL/6","bone marrow cells","L929-cell conditioned medium (LCCM)","30","% v/v","7","RPMI 1640 + 20% FBS","L18","R20/30 medium; 4 d then 3 d further incubation")
exc("PMC3003694","Bone marrow-derived dendritic cell protocol (GM-CSF, CD11c selection)","L26",M,"C57BL/6","bone marrow (femur/tibia)","GM-CSF","20","ng/ml","6","RPMI 1640")
# 8
inc("PMC11302253",M,NR,"bone marrow","M-CSF",NR,"NA","7","complete DMEM + 10% FCS","L42","Concentration of M-CSF not stated")
# 9
inc("PMC7047825",M,"C57BL/6","bone marrow","L-cell conditioned medium","20","% v/v","~7","DMEM + 10% FBS","L81,L14")
# 10
inc("PMC11417223",M,"C57BL/6N","bone marrow cells (femur/tibia)","M-CSF","20","ng/mL","7","DMEM GlutaMax + 10% FBS","L32,L72")
# 11
exc("PMC11144798","Porcine (pig) bone marrow-derived macrophages - not rodent","L6","pig","NA","porcine bone marrow (rib)","NA","NA","NA","NA","NA")
# 12
inc("PMC3574850",M,NR,"bone marrow cells (pelvic/femoral)","M-CSF","10","ng/ml","7","complete RPMI 1640 + 10% FBS","L58")
exc("PMC3574850","Bone marrow-derived dendritic cell protocol (GM-CSF + IL-4)","L60",M,NR,"bone marrow","GM-CSF + IL-4","10","ng/ml","7","complete RPMI 1640")
exc("PMC3574850","2 ng/ml M-CSF used for proliferation assay on already-purified macrophages, not differentiation","L68",M,NR,"purified bone marrow macrophages","M-CSF","2","ng/ml","4-14","complete RPMI 1640")
exc("PMC3574850","Spleen- and peritoneum-derived macrophages - not bone marrow","L68",M,NR,"spleen / peritoneal cavity","M-CSF","10","ng/ml","1","complete RPMI 1640")
# 13
inc("PMC11656472",M,"Cas9-expressing C57BL/6","bone marrow (femur)","L-cell supernatant (CSF1 source)","30","% v/v",NR,"DMEM + 20% heat-inactivated FBS","L48","Duration of differentiation not stated")
# 14
exc("PMC10893549","Bovine bone marrow-derived macrophages - not rodent","L1","cattle","NA","bovine bone marrow","NA","NA","NA","NA","NA")
# 15
inc("PMC7797923",M,NR,"bone marrow cells","M-CSF (CSF-1)","1","ng/mL","7","DMEM high glucose + 10% FBS","L20,L16","Protocol notes multiple concentrations may be tested; adherent BMDM assessed at day 4 and day 7")
# 16
exc("PMC12272449","Bone marrow transplantation / in vivo neuroinflammation study; no in vitro BMDM differentiation protocol","L14")
# 17
inc("PMC3750618",M,"C57BL/6","bone marrow (femur/tibia)","L929-conditioned medium (L-cell CM)","20","% v/v","7","RPMI 1640 + 10% FBS","L21")
# 18
inc("PMC12105080",M,"BALB/c","bone marrow cells","GM-CSF",NR,"NA",NR,NR,"L29","BMDMs generated by GM-CSF stimulation of bone marrow; concentration/duration not stated")
exc("PMC12105080","Bone marrow-derived dendritic cell (BMDC) protocol","L15",M,"BALB/c","bone marrow dendritic precursors","NA","NA","NA","NA","NA")
# 19
exc("PMC7119896","Abstract-only record in corpus; differentiation protocol details not available","L1")
# 20
inc("PMC3790761",M,"C57BL/6N","bone marrow cells","GM-CSF-conditioned medium (CHO-derived)","10","% v/v","10","RPMI 1640 + 10% FBS","L15","Adherent cells at day 10 collected as BM macrophages (BMMphi)")
exc("PMC3790761","Non-adherent fraction collected as bone marrow-derived dendritic cells","L15",M,"C57BL/6N","bone marrow","GM-CSF-conditioned medium","10","% v/v","10","RPMI 1640")
# 21
inc("PMC12800274",M,NR,"bone marrow cells","M-CSF","40","ng/ml","6","RPMI 1640 + 10% FBS","L209,L210")
# 22
inc("PMC6579556",M,NR,"bone marrow","M-CSF supernatant from 3T3-MCSF cells","10","% v/v",NR,"DMEM + 10% FBS","L15","BMM culture; differentiation duration not stated")
inc("PMC6579556",M,"Cas9+ mouse","bone marrow-derived ER-Hoxb8 immortalized progenitors (CIMs)","M-CSF supernatant from 3T3-MCSF cells","10","% v/v","9-10","DMEM + 10% FBS","L15","Differentiated after beta-estradiol withdrawal; progenitors originally derived from bone marrow")
# 23
inc("PMC11033405",M,"C57BL/6","bone marrow","M-CSF","25","ng/mL","7","DMEM + 10% FCS","L31")
# 24
exc("PMC4354151","Embryonic stem cell / embryoid body-derived macrophages - not bone marrow","L51",M,NR,"ESC-derived embryoid bodies","L929-conditioned medium","15","% v/v","7","RPMI 1640")
# 25
exc("PMC12562044","Equine periosteal and bone marrow-derived stem cells (osteogenesis) - not rodent, not macrophages","L7","horse","NA","equine bone marrow","NA","NA","NA","NA","NA")
# 26
inc("PMC5344453",M,"C57BL/6J","bone marrow progenitors (femur/tibia)","recombinant murine M-CSF","20","ng/ml","6","DMEM + GlutaMAX + 10% FBS","L28","2 d then adherent cells collected after 4 d")
inc("PMC5344453",M,"C57BL/6J","bone marrow progenitors (femur/tibia)","L-929 cell-conditioned medium","10","% v/v","6","DMEM + GlutaMAX + 10% FBS","L28","rmM-CSF replaced by 10% conditioned medium")
inc("PMC5344453",M,"C57BL/6J","bone marrow-derived ER-Hoxb8 immortalized myeloid progenitors","recombinant murine M-CSF","20","ng/ml","6","RPMI + GlutaMax + 10% FBS (Mac-Diff)","L33")
# 27
inc("PMC12478242",M,"C57BL/6","bone marrow cells (tibia/femur)","M-CSF","30","ng/mL","6-7","DMEM + 10% FBS","L33")
exc("PMC12478242","M1/M2 polarization step (LPS or TGF-beta1) after differentiation","L36",M,"C57BL/6","BMDM","LPS or TGF-beta1","NA","NA","1","DMEM")
# 28
inc("PMC11955436",M,NR,"bone marrow (tibiae/femurs)","L929 conditioned medium","20","% v/v","4-7","complete DMEM","L38")
# 29
inc("PMC7284309",M,NR,"bone marrow (cryopreserved)","L-cell conditioned medium (LCM)","10","% v/v","7","DMEM F12 + 10% FBS","L24")
inc("PMC7284309",M,NR,"bone marrow (cryopreserved)","M-CSF","25","ng/ml","7","DMEM F12 + 5% FBS","L28,L53","Optimised protocol: 50 ng/ml MCSF added day 5 and 50 ng/ml GM-CSF day 6")
# 30
exc("PMC11260838","Osteoclast differentiation protocol (M-CSF 5 ng/mL supplemental then M-CSF 100 + RANKL 100 ng/mL); no BMDM stage","L51",M,NR,"bone marrow cells","M-CSF + RANKL","100","ng/mL","3-6","alpha-MEM")
# 31
inc("PMC11245975",M,"C57BL/6J","bone marrow (one leg)","CSF-1","20","ng/mL","7","DMEM + 5% FCS","L22,L76")
exc("PMC11245975","Tissue-resident macrophage-like cultures (microglia, Kupffer, peritoneal, alveolar) - not bone marrow","L21,L23",M,"C57BL/6J","brain/liver/peritoneum/lung","CSF-1 + IL-34 or GM-CSF","20","ng/mL","14","DMEM")
# 32
inc("PMC11577564",M,"C57BL/6","bone marrow cells (femur/tibia)","L929 conditioned medium","30","% v/v","7","RPMI 1640 + 10% FBS","L20")
# 33
exc("PMC6838965","In vivo gene modification of tissue-resident peritoneal macrophages - no bone marrow protocol","L1")
# 34
inc("PMC11507697",M,"Hif1a-LysM conditional KO / floxed","bone marrow cells (femur/tibia)","M-CSF","40","ng/mL","7","RPMI 1640 + 10% FBS","L46","1 ug/ml 4-hydroxytamoxifen included for gene deletion")
# 35
inc("PMC7378060",M,"C57BL/6 (also BALB/c)","bone marrow cells","recombinant human M-CSF","100","ng/ml","5-7","RPMI 1640 + 10% FCS","L52")
# 36
exc("PMC11855042","Bone marrow transplant/lineage-tracing study of intraductal foam cells; no in vitro differentiation protocol","L9")
# 37
exc("PMC3679097","Human peripheral blood monocyte-derived macrophages (GM-CSF or M-CSF, 7 d)","L50","human","NA","human blood monocytes","GM-CSF or M-CSF",NR,"NA","7","NA")
# 38
exc("PMC12054994","Only a bibliographic mention of bone marrow-derived cells; no BMDM differentiation protocol","L156")
# 39
inc("PMC4620243",M,NR,"bone marrow cells","L929 cell-conditioned medium","30","% v/v","7","RPMI 1640 + 10% FBS","L21","M-BMM arm")
inc("PMC4620243",M,NR,"bone marrow cells","recombinant GM-CSF","20","ng/mL","7","RPMI 1640 + 10% FBS","L21","GM-BMM arm")
# 40
inc("PMC11326603",M,"C57BL/6","bone marrow cells (femora/tibiae)","L929 conditioned medium","30","% v/v","7","RPMI 1640 + 10% FBS","L70")
# 41
inc("PMC8034741",M,"C57BL/6","bone marrow cells (femur/tibia)","M-CSF from L929 cells","10","% v/v","7","complete DMEM","L20,L42")
exc("PMC8034741","Bone marrow-derived dendritic cell protocol (recombinant mouse GM-CSF)","L20",M,"C57BL/6","bone marrow","recombinant mouse GM-CSF","10-25","ng/ml","7-9","complete DMEM")
exc("PMC8034741","Bone marrow-derived dendritic cell protocol (HEK293T GM-CSF supernatant)","L20",M,"C57BL/6","bone marrow","GM-CSF-containing 293T supernatant","5-10","% v/v","7-9","complete DMEM")
# 42
exc("PMC10874407","Bone marrow stromal/mesenchymal stem cells, not macrophages","L13")
# 43
inc("PMC12514155",M,"BALB/c","bone marrow cells (femur/tibia)","M-CSF","20","ng/ml","5-7","RPMI 1640 + 10% FBS","L23")
# 44
inc("PMC12159446",M,"C57BL/6","total bone marrow cells (adult)","recombinant human M-CSF","100","ng/mL","5-6","RPMI 1640 + 10% FCS","L74,L81","M-CSF-dependent BM macrophage lines")
exc("PMC12159446","Fetal liver and yolk sac-derived macrophage lines - not bone marrow","L74",M,"C57BL/6","fetal liver (E14.5) / yolk sac (E9.5)","recombinant human M-CSF","100","ng/mL","5-6","RPMI 1640")
# 45
inc("PMC10944397",M,NR,"bone marrow cells (femur/tibiae)","mouse M-CSF","30","ng/ml","2","alpha-MEM + 10% FCS","L28","Adherent cells after 2 d defined as bone marrow macrophages (BMM)")
exc("PMC10944397","Osteoclast differentiation (M-CSF + RANKL) from BMM","L28",M,NR,"BMM","M-CSF + RANKL","30","ng/ml","3-4","alpha-MEM")
# 46
exc("PMC7119569","Feline bone marrow-derived macrophages - not rodent","L1","cat","NA","feline bone marrow","NA","NA","NA","NA","NA")
# 47
exc("PMC11762928","Only a bibliographic mention of BMDMs; no differentiation protocol","L116")
# 48
exc("PMC10206205","Peritoneal macrophage depletion/reconstitution protocol; no bone marrow differentiation","L5")
# 49
inc("PMC11971270",M,"Hif1a-/- and Hif1a+/+ (LysM-CreERT2)","bone marrow cells (femur/tibia)","M-CSF","40","ng/mL","7","RPMI 1640 + 10% FBS","L66")
# 50
exc("PMC4740517","Phagocytosis/bactericidal assay method; no bone marrow differentiation protocol","L1")
# 51
inc("PMC11988637",M,NR,"bone marrow cells (tibiae/femurs)","mouse M-CSF","30","ng/mL",NR,"alpha-MEM + 10% FBS","L39","Non-adherent cells after overnight culture become BMMs; duration not stated")
exc("PMC11988637","Osteoclast differentiation from BMMs (RANKL 100 ng/mL + M-CSF 30 ng/mL)","L43",M,NR,"BMM","RANKL + M-CSF","100","ng/mL","5","alpha-MEM")
# 52
inc("PMC7591151",M,"C57BL/6J","bone marrow","L929 conditioned medium","30","% v/v","6","DMEM (50%) + 20% heat-inactivated FBS","L170,L125")
# 53
exc("PMC6304906","In vivo Brucella persistence in bone marrow; no BMDM differentiation protocol","L1")
# 54
inc("PMC5104881",M,"C57BL/6J","bone marrow cells (femurs/tibiae)","murine GM-CSF","25","ng/ml","7","RPMI + 10% FBS","L15","GM-BMMs (MHCII-low F4/80-high) are the major attached population")
inc("PMC5104881",M,"C57BL/6J","bone marrow cells (femurs/tibiae)","murine GM-CSF","5","ng/ml","7","RPMI + 10% FBS","L35","Dose-response arm")
inc("PMC5104881",M,"C57BL/6J","bone marrow cells (femurs/tibiae)","murine GM-CSF","10","ng/ml","7","RPMI + 10% FBS","L35","Dose-response arm")
inc("PMC5104881",M,"C57BL/6J","bone marrow cells (femurs/tibiae)","murine GM-CSF","100","ng/ml","7","RPMI + 10% FBS","L35","Dose-response arm")
inc("PMC5104881",M,"C57BL/6J","bone marrow cells","L929 culture supernatant","20","% v/v","7","RPMI + 10% FBS","L23","M-CSF grown macrophages, sorted F4/80+CD11b+")
# 55
exc("PMC11135248","Bone marrow mesenchymal stem cell exosomes; not macrophage differentiation","L23")
# 56
exc("PMC6279884","Bone marrow adherent cells used directly; no differentiating agent stated","L16",M,NR,"bone marrow adherent cells","none stated","NA","NA","NA","NA")
# 57
inc("PMC11804269",M,"C57BL/6J","bone marrow (femur/tibia)","M-CSF","20","ng/ml",NR,"DMEM high-glucose + 10% FBS","L35","Baseline macrophage induction; duration not stated")
inc("PMC11804269",M,"C57BL/6J","bone marrow (femur/tibia)","recombinant mouse GM-CSF","20","ng/ml","7","DMEM high-glucose + 10% FBS","L36,L37","Cells designated M1-like")
inc("PMC11804269",M,"C57BL/6J","bone marrow (femur/tibia)","M-CSF","50","ng/ml","7","DMEM high-glucose + 10% FBS","L37","Cells designated M2-like")
# 58
exc("PMC6749721","Tissue (liver/spleen/lung/brain) macrophage-stromal co-culture without added CSF; not bone marrow","L20")
# 59
inc("PMC12191351",M,"WT and PD-1 KO","bone marrow cells (femur/tibia)","M-CSF","20","ng/mL","2","DMEM + 10% FBS + 50 uM 2-ME","L19")
# 60
exc("PMC11740880","Review of macrophage models; no original differentiation protocol","L73")
# 61
exc("PMC12607332","Bone marrow-derived dendritic cell protocol (GM-CSF +/- IL-4, 9-10 d)","L22,L58",M,NR,"bone marrow","GM-CSF + IL-4","10-20","ng/mL","9-10","RPMI 1640")
# 62
exc("PMC8468995","Lung tissue-resident macrophage/fibroblast co-culture without exogenous CSF; not bone marrow","L34")
# 63
exc("PMC12776085","In vivo CD8 T cell study; no BMDM differentiation protocol","L105")
# 64
exc("PMC8803360","Only bibliographic mentions of GM-CSF-driven alveolar macrophage development","L142")
# 65
inc("PMC12462494",M,"C57BL/6","bone marrow cells","L929 cell-conditioned medium","30","% v/v","7","RPMI 1640 + 10% FBS","L114")
inc("PMC12462494",M,"C57BL/6","bone marrow cells","recombinant M-CSF","20","ng/mL","7","RPMI 1640 + 10% FBS","L114")
# 66
inc("PMC9421540",M,NR,"bone marrow","recombinant murine M-CSF","20","ng/mL","7","DMEM + 10% FCS","L92,L26","Normoxia and hypoxia arms use the same medium")
inc("PMC9421540",M,NR,"bone marrow","recombinant murine M-CSF + IL-34 (20 ng/mL each)","20","ng/mL","7","DMEM + 10% FCS","L92","Hypoxia M-CSF & IL-34 arm")
inc("PMC9421540",M,NR,"bone marrow","recombinant murine GM-CSF","20","ng/mL","7","DMEM + 10% FCS","L92","Normoxia GM-CSF arm")
exc("PMC9421540","Tissue-resident macrophage-like cells (microglia, Kupffer, peritoneal, alveolar) - not bone marrow","L92",M,NR,"brain/liver/peritoneum/lung","M-CSF/IL-34 or GM-CSF","20","ng/mL","14","DMEM")
# 67
inc("PMC9498385",M,"C57BL/6J","bone marrow (femur/tibia)","L929-conditioned medium","30","% v/v","10","RPMI 1640 complete (70%)","L17,L19")
# 68
inc("PMC12368546",M,"C57BL/6","bone marrow (femurs/tibias)","M-CSF","20","ng/mL","7","high-glucose DMEM + 10% FBS","L81,L83")
# 69
inc("PMC8091624",M,"C57BL/6J","bone marrow cells","L929 conditioned media (LCCM)","20","% v/v","7","IMDM + 10% FBS","L55")
inc("PMC8091624",M,"C57BL/6J","bone marrow cells","recombinant M-CSF","10","ng/ml","7","IMDM + 10% FBS","L55")
inc("PMC8091624",M,"C57BL/6J","bone marrow cells","M-CSF 10 ng/ml + MIF 10 ng/ml","10","ng/ml","7","IMDM + 10% FBS","L55","MIF co-supplementation arm")
# 70
inc("PMC10712694",M,"C57BL/6","bone marrow cells (tibiae/femurs)","M-CSF","30","ng/ml","3","complete alpha-MEM + 10% FBS","L24","Preceded by 24 h in 10 ng/ml M-CSF; non-adherent cells then cultured 3 d in 30 ng/ml")
exc("PMC10712694","Osteoclast differentiation from BMDMs (M-CSF 30 + RANKL 75 ng/ml)","L24",M,"C57BL/6","BMDM","M-CSF + RANKL","75","ng/ml","3","alpha-MEM")
# 71
inc("PMC4061056",M,"BALB/c","bone marrow cells (femurs/tibiae)","L929-conditioned medium","30","% v/v","6","complete RPMI 1640 or advanced DMEM","L20")
exc("PMC4061056","Bone marrow-derived dendritic cell protocol (GM-CSF + IL-4)","L20",M,"BALB/c","bone marrow","GM-CSF + IL-4","20","ng/mL","6","complete RPMI or advanced DMEM")
# 72
exc("PMC12671093","Mouse parvovirus toxicity for human CD34+ precursors; no BMDM protocol","L1")
# 73
exc("PMC11496307","Review of macrophage model systems; no original differentiation protocol","L1")
# 74
exc("PMC11780875","Bone marrow mesenchymal stem cell extracellular vesicles; not macrophage differentiation","L7")
# 75
inc("PMC4640705",M,"BALB/cByJ","bone marrow (femora/tibiae)","L929 cell-conditioned medium 30% + M-CSF 10 ng/mL","30","% v/v",NR,"RPMI 1640 + 10% FBS","L17","Combined conditioned medium and recombinant M-CSF; duration not stated")
# 76
inc("PMC10844594",M,NR,"bone marrow","mouse M-CSF","20","ng/mL","7","IMDM + 20% FBS","L66")
exc("PMC10844594","Human bone marrow mononuclear cells with recombinant human M-CSF","L67","human","NA","human bone marrow mononuclear cells","recombinant human M-CSF","20","ng/mL","7","DMEM + 10% FBS")
# 77
inc("PMC8699930",M,"C57BL/6J","bone marrow-derived ER-Hoxb8 progenitor cells","M-CSF","10","ng/mL","5-6","RPMI 1640 + 10% FCS (+6% SCF supernatant)","L34,L80")
exc("PMC8699930","Yolk sac-derived ER-Hoxb8 progenitors - not bone marrow","L34",M,"C57BL/6J","yolk sac","M-CSF","10","ng/mL","5-6","RPMI 1640")
# 78
exc("PMC12589482","Human bone marrow MSCs/macrophages and RAW264.7 line","L23","human","NA","human bone marrow","NA","NA","NA","NA","NA")
# 79
exc("PMC2253558","RAW264.7 cell line study; no primary bone marrow differentiation","L1")
# 80
exc("PMC11176959","In vivo bone marrow histology/spatial transcriptomics; no BMDM culture","L25")
# 81
inc("PMC3511392",M,"C57BL/6N","bone marrow (femur)","recombinant M-CSF","6","ng/mL","14","RPMI 1640 + 5% FCS","L23")
# 82
exc("PMC12801197","No in vitro BMDM differentiation protocol (bone marrow niche/perlecan discussion)","L256")
# 83
exc("PMC5851575","Human monocyte-derived macrophages (M-CSF 100 ng/mL, 7 d) and PMA-treated THP-1","L39","human","NA","human blood monocytes","M-CSF","100","ng/mL","7","RPMI")
# 84
exc("PMC12747260","Bone marrow hemogenic endothelium/HSPC study; no BMDM protocol","L12")
# 85
inc("PMC8515861",M,NR,"bone marrow (femurs/tibia)","L929 fibroblast supernatant (M-CSF source)","20","% v/v","7","RPMI + 10% FCS","L20,L34")
inc("PMC8515861",M,NR,"bone marrow (femurs/tibia)","X63Ag8 supernatant (GM-CSF source)","20","% v/v","7","RPMI + 10% FCS","L20,L34")
# 86
exc("PMC12587627","Antimutagenicity study in mouse bone marrow in vivo; no macrophage differentiation","L1")
# 87
exc("PMC10518780","Bone marrow monocyte to alveolar macrophage-like differentiation by co-culture with lung epithelial cells and ILC2s; GM-CSF is ILC2-derived, no defined exogenous agent/concentration","L14",M,NR,"bone marrow monocytes","ILC2-derived GM-CSF","NA","NA","NA","NA")
# 88
exc("PMC12571368","Clinical bone marrow infection case series; no cell culture protocol","L1")
# 89
exc("PMC7645382","In vivo gene modification of peritoneal macrophages; no bone marrow protocol","L1")
# 90
exc("PMC11174124","Bone marrow- and adipose-derived mesenchymal stem cells; not macrophages","L7")
# 91
exc("PMC3768364","Mouse peritoneal macrophages","L1",M,NR,"peritoneum","NA","NA","NA","NA","NA")
# 92
inc("PMC11832192",M,"C57BL/6J (also KO and germ-free)","bone marrow","L929 cell supernatant (M-CSF source)","30","% v/v","5","complete RPMI","L81")
# 93
exc("PMC12086855","Alveolar macrophages from bronchoalveolar lavage cultured with GM-CSF - lavage, not bone marrow","L32",M,NR,"BALF alveolar macrophages","recombinant murine GM-CSF","15","ng/mL","NR","RPMI 1640")
# 94
inc("PMC11352128",M,"C57BL/6","bone marrow (tibia/femur)","M-CSF","1","ug/mL","5","DMEM/F12 + 10% FBS","L19","Differentiation assessed over 120 h; LPS added at 96 h")
# 95
exc("PMC4238769","Mouse peritoneal macrophages cultured with mouse serum","L369",M,NR,"peritoneum","mouse serum","NA","NA","NA","NA")
# 96
exc("PMC11318261","Porcine bone marrow-derived mesenchymal cells - not rodent, not macrophages","L1","pig","NA","porcine bone marrow","NA","NA","NA","NA","NA")
# 97
exc("PMC8691386","Splenic monocyte-derived macrophage niche; no bone marrow differentiation protocol","L1")
# 98
exc("PMC12733091","Bone marrow-derived mast cells - not macrophages","L7",M,NR,"bone marrow","NA","NA","NA","NA","NA")
# 99
inc("PMC12320229",M,"C57BL/6J","bone marrow cells (femurs/tibias)","M-CSF","20","ng/mL","7","DMEM + 10% FBS","L21")
exc("PMC12320229","Splenic macrophages cultured with M-CSF - spleen, not bone marrow","L98",M,"C57BL/6J","spleen","M-CSF","20","ng/mL","7","RPMI")
# 100
exc("PMC2186468","Abstract-only record in corpus; differentiation protocol text not available","L1")
# 101
exc("PMC12847970","Macrophage-conditioned medium effect on BMSCs; no BMDM differentiation protocol","L38")
# 102
inc("PMC5296737",M,"C57BL/6","bone marrow cells (femur/tibia)","M-CSF","20","ng/ml","7","DMEM + 10% heat-inactivated FBS","L48")
# 103
exc("PMC3741356","Human pluripotent stem cell-derived macrophages","L15","human","NA","hPSC-derived monocytes","M-CSF","100","ng/mL","5-7","X-VIVO 15 / RPMI")
# 104
exc("PMC11064454","Clinical case report of bone marrow infection; no cell culture","L1")
# 105
exc("PMC10234828","Bone marrow-derived dendritic cell protocol (GM-CSF + IL-4, 6 d)","L46",M,NR,"bone marrow","GM-CSF + IL-4","NA","NA","6","NA")
# 106
exc("PMC11929288","Osteoclast differentiation medium (M-CSF 25 ug/L + RANKL 50 ug/L); starting cells not defined as bone marrow","L51")
# 107
exc("PMC3317054","Primary rodent macrophages not derived from bone marrow (no bone marrow culture described)","L1")
# 108
inc("PMC12597883",M,NR,"bone marrow (femur/tibia)","recombinant M-CSF","50","ng/ml","6","RPMI 1640 + 10% FBS","L68")
exc("PMC12597883","Human PBMC-derived macrophages (M-CSF 50 ng/ml, 5 d)","L79","human","NA","human PBMC","M-CSF","50","ng/ml","5","RPMI + 10% FBS")
# 109
exc("PMC4278753","MuMac-E8 cell line; no primary bone marrow differentiation","L102")
# 110
inc("PMC11492788",M,NR,"bone marrow cells (femur)","M-CSF1","5","ng/ml","7","DMEM + 10% FBS","L35","Equal volume of medium with 10 ng/ml M-CSF1 added at day 4; BMDMs analysed at D7-D8")
# 111
exc("PMC5913604","Hematopoietic stem and progenitor cell study; no BMDM differentiation protocol","L1")
# 112
inc("PMC12289490",M,"C57BL/6","bone marrow (femurs/tibias)","M-CSF","10","ng/ml","7","DMEM + 10% FBS","L30")
# 113
exc("PMC2138492","Historical in vivo chromosome-marker study of macrophage origin; no culture protocol","L1")
# 114
exc("PMC12095274","Bone marrow mesenchymal stem cell conditioned medium; not macrophage differentiation","L10")
# 115
inc("PMC9299442",M,NR,"bone marrow cells (femurs)","M-CSF","50","ng/ml","7","DMEM + 10% FBS","L28")
inc("PMC9299442",M,NR,"bone marrow cells (femurs)","GM-CSF","20","ng/ml","7","DMEM + 10% FBS","L28")
# 116
exc("PMC11061410","Only bibliographic mentions of bone marrow-derived cells","L76")
# 117
exc("PMC12968255","Review of human monocyte-derived macrophage models","L28","human","NA","human monocytes","M-CSF or GM-CSF","5-100","ng/ml","6-7","NA")
# 118
exc("PMC11433566","Porcine bone marrow-derived dendritic cells (GM-CSF)","L12","pig","NA","porcine bone marrow","GM-CSF","NA","NA","10","NA")
# 119
exc("PMC2184262","Mouse peritoneal macrophages","L1",M,NR,"peritoneum","NA","NA","NA","NA","NA")
# 120
inc("PMC11878796",M,NR,"bone marrow","mouse M-CSF",NR,"NA",NR,NR,"L50","BMDMs differentiated with M-CSF; concentration, duration and medium not stated")
# 121
inc("PMC5062347",M,"C57BL/6","bone marrow (femur/tibia)","M-CSF","100","ng/mL","10","RPMI 1640 + 20% FBS","L47")
# 122
exc("PMC12443962","Bone marrow-derived B cells; not macrophages","L7")
# 123
exc("PMC10939251","RAW264.7 CRISPR method; no primary bone marrow differentiation","L1")
# 124
inc("PMC11220744",M,"C57BL/6NCrl and PER2::LUC","bone marrow","L cell conditioned medium","30","% v/v","7","RPMI 1640 + 10% Nu-Serum IV","L19")
# 125
exc("PMC4871654","Bone marrow-derived dendritic cell protocols (GM-CSF, GM-CSF+IL-15, GM-CSF+Flt3L)","L28",M,NR,"bone marrow","GM-CSF (J558L supernatant)","20","ng/mL","NA","NA")
# 126
exc("PMC12108605","Human bone marrow erythroid cells; not macrophages","L12","human","NA","human bone marrow erythroid cells","NA","NA","NA","NA","NA")
# 127
exc("PMC3526480","Resident alveolar macrophages (lavage); no bone marrow differentiation protocol","L1")
# 128
exc("PMC11110693","Bone marrow mesenchymal stem cell exosomes; not macrophage differentiation","L1")
# 129
exc("PMC10104118","Human PBMC/monocyte-derived alveolar macrophage-like cells (GM-CSF/TGF-beta/IL-10 + surfactant)","L65","human","NA","human PBMC","GM-CSF + TGF-beta + IL-10","10","ng/ml","6","NA")
# 130
exc("PMC11086728","Cord blood endothelial progenitor cells and humanized bone marrow niche; no BMDM protocol","L1")
# 131
exc("PMC7119689","Macrophage function during murine CMV infection; no bone marrow differentiation protocol in available text","L1")
# 132
exc("PMC11708448","Only a bibliographic mention of bone marrow-derived plasma cells","L472")
# 133
exc("PMC3686598","Review of human monocyte-derived macrophage differentiation (M-CSF vs GM-CSF)","L7","human","NA","human blood monocytes","M-CSF or GM-CSF","NA","NA","NA","NA")
# 134
exc("PMC12395819","Bone marrow mesenchymal stem cell migrasomes; not macrophage differentiation","L1")
# 135
exc("PMC4632742","Comparison of antigen-presenting cell models; no differentiating agent or bone marrow protocol stated","L12")
# 136
exc("PMC11054941","BMDMs used for infection experiments but no differentiation agent/protocol stated","L10")
# 137
exc("PMC4437037","Only a bibliographic mention of GM-CSF-driven alveolar macrophage development","L131")
# 138
exc("PMC11438345","Only a bibliographic mention of bone marrow stromal cell conditioned medium","L457")
# 139
inc("PMC524361","Peromyscus maniculatus","deer mouse (outbred)","bone marrow cells (cryopreserved)","recombinant house mouse GM-CSF","20","ng/ml","10-14","DMM-10","L65,L26","Bone marrow-derived antigen-presenting cells; authors note the cells resembled macrophages rather than dendritic cells")
# 140
exc("PMC11637496","MSC-HSC co-culture; no macrophage differentiation protocol","L57")
# 141
inc("PMC4121081",M,NR,"bone marrow cells (cryopreserved)","L929 cell conditioned medium","20","% v/v","6-7","complete RPMI","L26")
# 142
exc("PMC12173640","Protocol for alveolar bone marrow hematopoietic stem cell isolation; no macrophage differentiation","L1")
# 143
exc("PMC2188919","Abstract-only record in corpus; differentiation protocol text not available","L1")
# 144
exc("PMC11770371","BMDM-derived extracellular vesicle study; no in vitro differentiation protocol stated","L38")
# 145
inc("PMC11253027",M,NR,"bone marrow-derived monocytes (magnetically isolated)","CSF1","20","ng/mL","7","Opti-MEM + 10% FBS","L38,L68")
# 146
exc("PMC10031535","Human monocyte-derived macrophages (recombinant human M-CSF 25 ng/mL)","L29","human","NA","human monocytes","recombinant human M-CSF","25","ng/mL","NA","X-VIVO-15 or RPMI")
# 147
inc("PMC11034578","rat","Sprague-Dawley","bone marrow mononuclear cells (femur/tibia)","recombinant rat M-CSF","20","ng/mL","7","DMEM high glucose + 10% FBS","L16,L67")
# 148
exc("PMC11419857","Only a bibliographic mention of GM-CSF-driven alveolar macrophage development","L113")
# 149
exc("PMC12106512","L929 fibroblast culture on scaffolds; not a bone marrow macrophage protocol","L18")
# 150
inc("PMC3743904",M,"BALB/c","bone marrow (femurs/tibias)","L-cell conditioned media","20","% v/v",NR,"supplemented RPMI 1640","L252,L253","Differentiation duration not stated")
# 151
exc("PMC11305850","Only a bibliographic mention of bone marrow-derived endothelial cells","L283")
# 152
exc("PMC5027544","Toxoplasma excystation in macrophages; no bone marrow differentiation protocol in available text","L1")
# 153
exc("PMC11785368","Review of CSF1R biology and tissue macrophages; no original protocol","L17")
# 154
inc("PMC4834433",M,"C57BL/6 / BALB/c","bone marrow (femurs/tibias)","L929 cell supernatant (M-CSF source)","30","% v/v","4","RPMI 1640 + 10% FBS","L18")
# 155
exc("PMC12837519","Human bone marrow mesenchymal stem cells; not macrophages","L11","human","NA","human bone marrow MSC","NA","NA","NA","NA","NA")
# 156
exc("PMC12132487","Mouse EpiSC/ESC-derived tissue-resident macrophages (M-CSF + IL-34) - not bone marrow","L57,L60",M,"B6/129 EpiSC lines","pluripotent stem cell-derived","M-CSF + IL-34","100","ng/mL","NA","IMDM/F12 + B27")
# 157
exc("PMC11588629","Only a bibliographic mention of bone marrow MSC exosomes","L163")
# 158
exc("PMC9812659","Chicken bone marrow-derived macrophages/dendritic cells - not rodent","L17","chicken","NA","chicken bone marrow","CSF1","200","ng/mL","2-8","complete RPMI")
# 159
inc("PMC11776149","rat",NR,"bone marrow (femur/tibia)","M-CSF","10","ng/ml",NR,NR,"L15","Duration and base medium not stated")
# 160
exc("PMC2138781","Historical study of mouse hepatitis virus and macrophages; no bone marrow differentiation protocol available","L1")
# 161
inc("PMC11395440",M,NR,"bone marrow (femur/tibia)","L929 culture supernatant",NR,"% v/v","10","DMEM (400 mg/L glucose) + 10% FBS","L62","Percentage of L929 supernatant not stated")
# 162
exc("PMC4786427","BMDMs generated as previously described; no differentiating agent or protocol stated","L102")
# 163
exc("PMC11044677","Bone marrow endothelial progenitor cells in lung injury; no BMDM protocol","L189")
# 164
exc("PMC4778410","Macrophage bacterial-killing study; no bone marrow differentiation protocol in available text","L1")
# 165
exc("PMC12275069","Osteoclastogenesis from bone marrow cells (M-CSF 20 ng/mL + RANKL 100 ng/mL, 9-10 d)","L22",M,"C57BL/6N","bone marrow (tibias/femurs)","M-CSF + RANKL","20","ng/mL","9-10","alpha-MEM + 10% FBS")
# 166
exc("PMC12404969","Review; only general statements about 5-7 day M-CSF/L929 BMDM induction","L26")
# 167
exc("PMC12199399","Macrophage-derived EVs and BMSC fate; no BMDM differentiation protocol","L1")
# 168
exc("PMC13253848","Bacterial neuroinvasion study; no in vitro BMDM differentiation protocol","L8")
# 169
exc("PMC12561077","Review of myeloid differentiation; no original protocol","L16")
# 170
exc("PMC2427050","Alveolar macrophages (lavage) cultured with M-CSF 10 ng/ml - not bone marrow","L50",M,NR,"alveolar macrophages","M-CSF","10","ng/ml","NA","DMEM + 15% FBS")
# 171
exc("PMC12608139","Myelosuppression study; no BMDM differentiation protocol","L1")
# 172
exc("PMC3842019","M-CSF administered in vivo (i.p.); no in vitro bone marrow differentiation protocol","L34")
# 173
exc("PMC12384577","Porcine and human monocyte-derived macrophages","L66","pig/human","NA","blood monocytes","GM-CSF or M-CSF","NA","NA","NA","NA")
# 174
exc("PMC4422593","Human iPSC-derived macrophages (IL-3 + M-CSF)","L18","human","NA","iPSC-derived myeloid precursors","M-CSF","100","ng/ml","NA","NA")
# 175
inc("PMC10906463",M,"C57BL/6J","bone marrow (tibia/femur)","mouse M-CSF1","1","ng/mL","6","DMEM high glucose + 10% FBS","L68")
# 176
exc("PMC3427505","BMDMs referred to as generated in MCSF-containing media; no concentration, duration or medium stated","L52")
# 177
inc("PMC12851398",M,NR,"bone marrow (femurs/tibias)","M-CSF","0.5","ug/mL","7","Hibernate media + 10% FBS","L28","M2 control macrophages")
inc("PMC12851398",M,NR,"bone marrow (femurs/tibias)","GM-CSF","0.5","ug/mL","7","Hibernate media + 10% FBS","L28","M1 control macrophages")
exc("PMC12851398","Glioma-educated TAM protocol uses tumor-conditioned medium plus IL-4 and IL-10 alongside M-CSF (polarization)","L28",M,NR,"bone marrow","M-CSF + IL-4 + IL-10 in tumor-conditioned media","0.5","ug/mL","7","TCM:Hibernate 1:1")
# 178
inc("PMC10689348",M,"C57BL/6JJcl / BALB/cAJcl","bone marrow (femora)","M-CSF","2","ng/ml","6-10","DMEM + 10% FBS","L37")
# 179
exc("PMC11253522","In vivo fate mapping of bone marrow-derived myeloid cells in brain; no culture protocol","L14")
# 180
inc("PMC8669096",M,NR,"bone marrow cells","L929 conditioned medium","30","% v/v","7","complete RPMI 1640 (70%)","L41,L62")
# 181
inc("PMC11008274",M,"C57BL/6","bone marrow cells (tibia/femur)","L929 conditioned media","10","% v/v","7","DMEM + 10% FBS","L54")
# 182
exc("PMC4116603","Osteoblast and macrophage responses to S. aureus; no bone marrow differentiation protocol in available text","L1")
# 183
inc("PMC11734715",M,NR,"bone marrow cells","recombinant murine M-CSF","20","ng/ml",NR,"DMEM + 10% heat-inactivated FBS","L67","Duration not stated")
# 184
inc("PMC2134957",M,"129SvEvTac","bone marrow stem cells (femurs/humeri)","GM-CSF","10","ng/ml","6","DMEM + 10% heat-inactivated FBS","L50")
# 185
exc("PMC12264857","Equine bone marrow mesenchymal stem cells - not rodent, not macrophages","L1","horse","NA","equine bone marrow MSC","NA","NA","NA","NA","NA")
# 186
exc("PMC9481898","Human pluripotent stem cell-derived macrophages (M-CSF)","L1","human","NA","hPSC-derived","M-CSF","50","ng/ml","NA","Magec medium")
# 187
exc("PMC12675402","Only a bibliographic mention of bone marrow stromal cells","L555")
# 188
inc("PMC11818227",M,NR,"bone marrow cells (femurs/tibias)","L929-conditioned medium (M-CSF source)","20","% v/v","7","DMEM/F12 + 10% FBS","L49")
exc("PMC11818227","Human blood monocyte-derived macrophages (M-CSF 100 ng/mL, 5 d)","L52","human","NA","human blood monocytes","M-CSF","100","ng/mL","5","TexMACS")
# 189
exc("PMC11070863","Biomaterial-mediated macrophage polarization study; no bone marrow differentiation protocol in available text","L1")
# 190
inc("PMC3424254",M,"BALB/c","bone marrow (femurs/tibias)","M-CSF","80","ng/ml","7","RPMI 1640 + 10% FCS","L24","Overnight pre-incubation to remove stromal cells, then 7 d differentiation")
# 191
inc("PMC11070510",M,"BALB/c (WT and Tlr2 KO)","bone marrow cells (femurs)","GM-CSF 40 ng/mL + M-CSF 20 ng/mL","40","ng/mL","10","RPMI 1640 + 10% FBS","L22","Both cytokines used together")
# 192
exc("PMC9471451","Bone marrow-derived dendritic cell protocol (GM-CSF 10-25 ng/mL, 7-8 d)","L45",M,NR,"bone marrow","GM-CSF","20","ng/mL","7-8","DC medium")
# 193
exc("PMC10699128","Ebolavirus study in rhesus macaques; not rodent, no BMDM protocol","L1","macaque","NA","NA","NA","NA","NA","NA","NA")
# 194
exc("PMC4894436","siRNA screening cell system in human and mouse macrophages; no bone marrow differentiation protocol in available text","L1")
# 195
exc("PMC12078524","Fetal bone marrow/liver hematopoiesis; no macrophage differentiation protocol","L1")
# 196
exc("PMC7874634","Immortalized mouse C57Bl/6 BMDM line; no differentiation protocol","L14",M,"C57BL/6","immortalized BMDM line","NA","NA","NA","NA","NA")
# 197
exc("PMC10864772","Bone marrow-derived exosomes and granulosa cells; no BMDM differentiation protocol","L229")
# 198
exc("PMC7984372","Review of mediators for in vitro modelling of human macrophages","L1","human","NA","human monocytes","NA","NA","NA","NA","NA")
# 199
inc("PMC11297156",M,"C57BL/6","bone marrow monocytes (femur/tibia)","M-CSF","25","ng/ml","10","DMEM + 10% FBS","L81")
# 200
exc("PMC2118235","Blood monocytes cultured 2 d with GM-CSF toward a dendritic cell phenotype","L36",M,"BALB/c","blood leukocytes","GM-CSF","NA","NA","2","NA")

with open("results.tsv","w",encoding="utf-8") as f:
    f.write(HEADER+"\n")
    for r in R:
        assert len(r)==12, r
        f.write("\t".join(str(x).replace("\t"," ") for x in r)+"\n")
print("rows",len(R))
